export const TOPICS = [
  "General Question",
  "Exercise 0",
  "OS Fundamentals",
  "Exercise 1",
  "Project 0",
  "Processes & Threads",
  "Exercise 2",
  "Interprocess Communication & Synchronization",
  "Exercise 3",
  "Process Scheduling",
  "Exercise 4",
  "Memory Management",
  "Exercise 5",
  "Virtual Memory",
  "Exercise 6",
  "Exam 1",
  "Filesystem Fundamentals",
  "Exercise 7",
  "Filesystem Implementation",
  "Exercise 8",
  "I/O Devices",
  "Exercise 9",
  "Networking",
  "Project 1",
  "Project 2",
  "Deadlocks",
  "Project 3",
  "Security",
  "Exam 2"
];